config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :boards
  resources :comments, only: %i[create destroy]
  resources :users, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  title      :string(255)
#  body       :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Board < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations
  has_many :tags, through: :board_tag_relations

  validates :name, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/board_tag_relation.rb
# == Schema Information
#
# Table name: board_tag_relations
#
#  id         :bigint(8)        not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint(8)
#  tag_id     :bigint(8)
#
# Indexes
#
#  index_board_tag_relations_on_board_id  (board_id)
#  index_board_tag_relations_on_tag_id    (tag_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (tag_id => tags.id)
#

class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint(8)        not null, primary key
#  comment    :text(65535)
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint(8)
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#

class Comment < ApplicationRecord
  belongs_to :board
  validates :name, presence: true, length: { maximum: 10 }
  validates :comment, presence: true, length: { maximum: 1000 }
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_many :board_tag_relations, dependent: :delete_all
  has_many :boards, through: :board_tag_relations
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  birthday        :date
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#

class User < ApplicationRecord
  has_secure_password

  validates :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 16 },
    format: {
      with: /\A[a-z0-9]+\z/,
      message: 'は小文字英数字で入力してください'
    }
  validates :password,
    length: { minimum: 8 }

  def age
    now = Time.zone.now
    (now.strftime('%Y%m%d').to_i - birthday.strftime('%Y%m%d').to_i) / 10000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy]

  def index
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.page(params[:page])
  end

  def new
    @board = Board.new(flash[:board])
  end

  def create
    board = Board.new(board_params)
    if board.save
      flash[:notice] = "「#{board.title}」の掲示板を作成しました。"
      redirect_to board
    else
      redirect_to new_board_path, flash: {
        board: board,
        error_messages: board.errors.full_messages
      }
    end
  end

  def show
    @comment = Comment.new(board_id: @board.id)
  end

  def edit
    @board.attributes = flash[:board] if flash[:board]
  end

  def update
    if @board.update(board_params)
      redirect_to @board, flash: { notice: "「#{@board.title}」の掲示板を編集しました。" }
    else
      redirect_to edit_board_path, flash: {
        board: @board,
        error_messages: @board.errors.full_messages
      }
    end
  end

  def destroy
    @board.destroy

    redirect_to boards_path, flash: { notice: "#{@board.title}の掲示板が削除されました。" }
  end

  private

  def board_params
    params.require(:board).permit(:name, :title, :body, tag_ids: [])
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = 'コメントを投稿しました。'
      redirect_to comment.board
    else
      flash[:comment] = comment
      flash[:error_messages] = comment.errors.full_messages
      redirect_back fallback_location: comment.board
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to comment.board, flash: { notice: 'コメントが削除されました' }
  end

  private

  def comment_params
    params.require(:comment).permit(:board_id, :name, :comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      render 'home/index'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      flash[:user] = user
      flash[:error_messages] = user.errors.full_messages
      redirect_back fallback_location: new_user_path
    end
  end

  def me
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BoardApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= header_link_item('ホーム', root_path) %>
      </li>
      <li class="nav-item">
        <%= header_link_item('掲示板一覧', boards_path) %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if @current_user %>
            <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
            <%= link_to 'ログイン', root_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
    <% board.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
  </div>
</div>

app/views/boards/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: board do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= form_with url: boards_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
      {
        prompt: 'タグで絞り込み',
        class: 'form-control boards__select',
        onchange: 'submit(this.form);'
      }
      %>
    <% end %>
    <%= link_to '新規作成', new_board_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<% if flash[:notice] %>
  <div class="alert alert-danger">
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.name %></td>
        <td><%= board.created_at.to_s(:datetime_jp) %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-primary">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= render @board %>

<div class="p-comment__list">
  <div class="p-comment_listTitle">コメント</div>
  <%= render @board.comments %>
</div>

<%= render partial: 'comments/form', locals: { comment: @comment } %>

app/views/comments/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= comment.name %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
    <span><%= link_to '削除', comment, method: :delete, data: { confirm: '削除してもよろしいですか？' } %></span>
  </div>
</div>

app/views/comments/_form.html.erb
<%= render 'shared/error_messages' %>

<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_with model: comment do |f| %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 5 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render partial: 'users/login_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/users/_login_form.html.erb
<h1>ログイン</h1>

<%= form_with scope: :session, url: login_path do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'ログイン', class: 'btn btn-primary' %>
<% end %>

app/views/users/me.html.erb
<h1>マイページ</h1>
<p><%= @current_user.name %></p>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= render partial: 'form', locals: { user: @user } %>